services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: server
        env_file: .env
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - ./server:/app
            - /app/node_modules
        networks:
            - node-ollama-network

    ollama-client:
        image: ollama/ollama
        volumes:
            - ./ollama:/root/.ollama
        ports:
            - "${OLLAMA_PORT}:${OLLAMA_PORT}"
        networks:
            - node-ollama-network

networks:
    node-ollama-network:
        driver: bridge
