FROM node:lts-alpine

WORKDIR /app

COPY package*.json yarn.lock ./

RUN yarn install

RUN mkdir -p /app/db && chmod 777 /app

COPY --chown=node:node . .

USER node

EXPOSE ${SERVER_PORT}

CMD ["yarn", "dev"]